# Generated by Django 5.2.6 on 2025-09-10 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Buy Now', max_length=50)),
                ('trapezoid_image', models.ImageField(upload_to='hero/trapezoid/')),
                ('bike_image', models.ImageField(upload_to='hero/bike/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='InfoSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Read More', max_length=50)),
                ('bike_image', models.ImageField(upload_to='info_section/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='SupportFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(blank=True, max_length=140)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='support_features/')),
                ('arrow_image', models.ImageField(blank=True, null=True, upload_to='support_features/arrows/')),
                ('arrow', models.CharField(choices=[('up', 'Up'), ('down', 'Down')], default='up', max_length=4)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
