# Generated by Django 5.2.6 on 2025-09-10 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0002_location_buybike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybike',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='review_count',
        ),
    ]
