# Generated by Django 5.2.6 on 2025-09-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0003_remove_buybike_rating_remove_buybike_review_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybike',
            name='bike_model',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='buybike',
            name='bike_variant',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buybike',
            name='finance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buybike',
            name='insurance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buybike',
            name='owners',
            field=models.CharField(blank=True, choices=[('1st Owner', '1st Owner'), ('2nd Owner', '2nd Owner'), ('3rd Owner', '3rd Owner'), ('4th+ Owner', '4th+ Owner')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buybike',
            name='refurbished',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buybike',
            name='registration_certificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buybike',
            name='registration_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='buybike',
            name='rto_city',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buybike',
            name='rto_state',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='buybike',
            name='transmission',
            field=models.CharField(blank=True, choices=[('manual', 'Manual'), ('auto', 'Auto'), ('semi-auto', 'Semi-Auto')], max_length=12, null=True),
        ),
        migrations.AddField(
            model_name='buybike',
            name='warranty',
            field=models.BooleanField(default=False),
        ),
    ]
