# Generated by Django 5.2.6 on 2025-09-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0005_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buybike',
            name='bike_model',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='bike_variant',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='finance',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='insurance',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='refurbished',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='registration_certificate',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='registration_year',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='rto_city',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='rto_state',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='transmission',
        ),
        migrations.RemoveField(
            model_name='buybike',
            name='warranty',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
