# Generated by Django 5.2.6 on 2025-09-11 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0008_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='booking_steps/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Smaller numbers appear first.')),
                ('active', models.BooleanField(default=True, help_text='Uncheck to hide this step from the public site.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Booking Step',
                'verbose_name_plural': 'Booking Steps',
                'ordering': ('order',),
            },
        ),
    ]
