# Generated by Django 5.2.6 on 2025-09-11 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0009_bookingstep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookingstep',
            name='description',
        ),
        migrations.RemoveField(
            model_name='bookingstep',
            name='subtitle',
        ),
    ]
