# Generated by Django 5.2.6 on 2025-09-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0010_remove_bookingstep_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('subtitle', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Last Section',
                'verbose_name_plural': 'Last Sections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LastSectionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Upload the step image', upload_to='last_section/')),
                ('title', models.CharField(blank=True, help_text='Image title / caption', max_length=255, null=True)),
                ('order_no', models.PositiveSmallIntegerField(default=0, help_text='Order (0 = first)')),
                ('alt_text', models.CharField(blank=True, help_text='Optional alt text for accessibility', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bike.lastsection')),
            ],
            options={
                'verbose_name': 'Last Section Image',
                'verbose_name_plural': 'Last Section Images',
                'ordering': ['order_no', 'pk'],
            },
        ),
        migrations.DeleteModel(
            name='BookingStep',
        ),
    ]
