# Generated by Django 5.2.6 on 2025-09-11 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0011_lastsection_lastsectionimage_delete_bookingstep'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybike',
            name='abs',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='buybike',
            name='front_brake_type',
            field=models.CharField(blank=True, help_text='e.g. Drum / Disc', max_length=120),
        ),
        migrations.AddField(
            model_name='buybike',
            name='ignition_type',
            field=models.CharField(blank=True, help_text='e.g. Kick & Self Start', max_length=120),
        ),
        migrations.AddField(
            model_name='buybike',
            name='odometer',
            field=models.CharField(blank=True, choices=[('analogue', 'Analogue'), ('digital', 'Digital'), ('both', 'Both')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='buybike',
            name='rear_brake_type',
            field=models.CharField(blank=True, help_text='e.g. Drum / Disc', max_length=120),
        ),
        migrations.AddField(
            model_name='buybike',
            name='wheel_type',
            field=models.CharField(blank=True, help_text='e.g. Steel / Alloy', max_length=120),
        ),
        migrations.AlterField(
            model_name='buybike',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='buybikes/images/'),
        ),
    ]
