# Generated by Django 5.2.6 on 2025-09-11 16:39

import bike.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0012_buybike_abs_buybike_front_brake_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Big heading text', max_length=255)),
                ('background_image', models.ImageField(blank=True, null=True, upload_to=bike.models.banner_upload_to)),
                ('logo', models.ImageField(blank=True, null=True, upload_to=bike.models.banner_upload_to)),
                ('bike_image', models.ImageField(blank=True, help_text='Decorative bike image (left)', null=True, upload_to=bike.models.banner_upload_to)),
                ('star_image', models.ImageField(blank=True, help_text='Star icon (rating)', null=True, upload_to=bike.models.banner_upload_to)),
                ('badge_image', models.ImageField(blank=True, help_text='Badge icon (experience)', null=True, upload_to=bike.models.banner_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='StatItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(blank=True, null=True, upload_to=bike.models.stat_icon_upload_to)),
                ('value', models.CharField(max_length=64)),
                ('caption', models.CharField(max_length=128)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('banner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='bike.homepagebanner')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
