# Generated by Django 5.2.6 on 2025-09-11 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0013_homepagebanner_statitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepagebanner',
            name='background_image',
        ),
        migrations.RemoveField(
            model_name='homepagebanner',
            name='badge_image',
        ),
        migrations.RemoveField(
            model_name='homepagebanner',
            name='bike_image',
        ),
        migrations.RemoveField(
            model_name='homepagebanner',
            name='star_image',
        ),
    ]
