# Generated by Django 5.2.6 on 2025-09-11 17:02

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0014_remove_homepagebanner_background_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('role', models.CharField(blank=True, max_length=128, null=True)),
                ('quote', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to=bike.models.testimonial_image_upload_to)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('order', 'created_at'),
            },
        ),
        migrations.CreateModel(
            name='TestimonialsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Real Stories From our Happy Customer', max_length=255)),
                ('subtitle', models.CharField(blank=True, default='Their words drive us forward and inspire others to join the movement.', max_length=512, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
