# Generated by Django 5.2.6 on 2025-09-11 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0017_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='buybike',
            name='variant_image1',
            field=models.ImageField(blank=True, null=True, upload_to='buybikes/variants/'),
        ),
        migrations.AddField(
            model_name='buybike',
            name='variant_image2',
            field=models.ImageField(blank=True, null=True, upload_to='buybikes/variants/'),
        ),
        migrations.AddField(
            model_name='buybike',
            name='variant_image3',
            field=models.ImageField(blank=True, null=True, upload_to='buybikes/variants/'),
        ),
        migrations.AddField(
            model_name='buybike',
            name='variant_image4',
            field=models.ImageField(blank=True, null=True, upload_to='buybikes/variants/'),
        ),
        migrations.AddField(
            model_name='buybike',
            name='variant_image5',
            field=models.ImageField(blank=True, null=True, upload_to='buybikes/variants/'),
        ),
    ]
