# Generated by Django 5.2.6 on 2025-09-12 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0018_buybike_variant_image1_buybike_variant_image2_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='herosection',
            options={},
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='bike_image',
        ),
        migrations.RemoveField(
            model_name='herosection',
            name='order',
        ),
        migrations.CreateModel(
            name='HeroBikeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='hero/bike/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('hero_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bike_images', to='bike.herosection')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
