# Generated by Django 5.2.6 on 2025-09-12 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0019_alter_herosection_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('section1', 'Section 1'), ('section2', 'Section 2'), ('section3', 'Section 3')], max_length=20, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('overlay_title', models.CharField(blank=True, max_length=100, null=True)),
                ('overlay_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AboutSection3Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('section3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bike.aboutsection')),
            ],
        ),
    ]
