# Generated by Django 5.2.6 on 2025-09-12 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0020_aboutsection_aboutsection3image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(default='Contact Us', max_length=255)),
                ('subheading', models.CharField(blank=True, max_length=512, null=True)),
                ('address', models.TextField(blank=True, help_text='Full address/line breaks allowed', null=True)),
                ('map_embed_url', models.URLField(blank=True, help_text='Full Google Maps share URL (embed or map link)', null=True)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('reason_choices', models.JSONField(blank=True, default=list, help_text="JSON array of strings for 'Reason to Contact' dropdown", null=True)),
                ('found_us_choices', models.JSONField(blank=True, default=list, help_text="JSON array of strings for 'How did you find us?' dropdown", null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.RemoveField(
            model_name='aboutsection3image',
            name='section3',
        ),
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=64, null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('found_us', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_email', models.BooleanField(default=False)),
                ('config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submissions', to='bike.contactconfig')),
            ],
        ),
        migrations.DeleteModel(
            name='AboutSection',
        ),
        migrations.DeleteModel(
            name='AboutSection3Image',
        ),
    ]
