# Generated by Django 5.2.6 on 2025-09-12 14:42

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0021_contactconfig_remove_aboutsection3image_section3_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to=bike.models.auth_image_upload_to)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auth Image',
                'verbose_name_plural': 'Auth Images',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='AuthPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(blank=True, help_text='If set, registration notification emails will be sent here. Otherwise EMAIL_HOST_USER is used.', max_length=254, null=True)),
                ('send_welcome_email', models.BooleanField(default=True, help_text='Send a welcome email to user after registration')),
                ('is_active', models.BooleanField(default=True, help_text='Only the latest active config is used by the frontend')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Auth Page Config',
                'verbose_name_plural': 'Auth Page Configs',
                'ordering': ('-created_at',),
            },
        ),
    ]
