# Generated by Django 5.2.6 on 2025-09-12 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0023_aboutsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutSection',
        ),
    ]
