# Generated by Django 5.2.6 on 2025-09-12 16:13

import bike.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0024_delete_aboutsection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSectionOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=255, null=True)),
                ('content', models.TextField(blank=True, help_text='HTML allowed', null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=bike.models.about_section_upload_to)),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Only active records are used by the frontend')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers show first if multiple records')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'About Section 1',
                'verbose_name_plural': 'About Section 1s',
                'ordering': ('order', '-created_at'),
            },
        ),
    ]
