# Generated by Django 5.2.6 on 2025-09-12 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0025_aboutsectionone'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellBikePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_banner_image', models.ImageField(upload_to='sellbike/')),
                ('top_banner_text', models.TextField()),
                ('second_banner_image', models.ImageField(upload_to='sellbike/')),
                ('second_banner_top_text', models.TextField(blank=True, help_text='Supports HTML tags', null=True)),
                ('second_banner_bottom_text', models.CharField(blank=True, max_length=200, null=True)),
                ('brand_options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('model_options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('variant_options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('year_options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('kms_options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('owner_options', models.TextField(blank=True, help_text='Comma separated values', null=True)),
                ('third_title', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='HowItWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='sellbike/')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='how_it_works', to='bike.sellbikepage')),
            ],
        ),
    ]
