# Generated by Django 5.2.6 on 2025-09-12 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0026_sellbikepage_howitworks'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HowItWorks',
        ),
        migrations.DeleteModel(
            name='SellBikePage',
        ),
    ]
