# Generated by Django 5.2.6 on 2025-09-12 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bike', '0027_delete_howitworks_delete_sellbikepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Us', max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='about/section1/')),
            ],
            options={
                'verbose_name': 'About - Section 1',
                'verbose_name_plural': 'About - Section 1',
            },
        ),
        migrations.CreateModel(
            name='AboutSection2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background_image', models.ImageField(upload_to='about/section2/')),
                ('overlay_title', models.CharField(blank=True, max_length=255)),
                ('overlay_text', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About - Section 2',
                'verbose_name_plural': 'About - Section 2',
            },
        ),
        migrations.CreateModel(
            name='AboutSection3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Our Approach', max_length=255)),
                ('content', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'About - Section 3',
                'verbose_name_plural': 'About - Section 3',
            },
        ),
        migrations.CreateModel(
            name='AboutSection3Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/section3/')),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bike.aboutsection3')),
            ],
            options={
                'verbose_name': 'About - Section 3 Image',
                'verbose_name_plural': 'About - Section 3 Images',
                'ordering': ('order',),
            },
        ),
    ]
